apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-poc-billing
  labels:
    app.wp.poc/name: wp-billing
spec:
  replicas: 1
  selector:
    matchLabels:
      app.wp.poc/name: wp-billing
  template:
    metadata:
      labels:
        app.wp.poc/name: wp-billing
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: kafka-topic-setup
          image: rhorv/kafka-adm:latest
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "/tmp/kafka_2.13-2.8.0/bin/kafka-topics.sh --create --if-not-exists --topic $${EXTERNAL_TOPIC_NAME} --bootstrap-server $${KAFKA_HOST}:$${KAFKA_PORT} && /tmp/kafka_2.13-2.8.0/bin/kafka-topics.sh --create --if-not-exists --topic $${INTERNAL_TOPIC_NAME} --bootstrap-server $${KAFKA_HOST}:$${KAFKA_PORT}"]
          env:
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: host
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: port
            - name: EXTERNAL_TOPIC_NAME
              value: "billing-payment"
            - name: INTERNAL_TOPIC_NAME
              value: "billing-internal"
        - name: db-migration
          image: rhorv/wp-poc-db-infra:19ccb6267ca9da27bf75773b827d1bf304ae8b09
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "flyway -locations=filesystem:/srv/billing -user=$${PG_BILLING_USER} -password=$${PG_BILLING_PASS} -url=jdbc:postgresql://$${PG_BILLING_HOST}:$${PG_BILLING_PORT}/$${PG_BILLING_DB} migrate"]
          env:
            - name: PG_BILLING_HOST
              valueFrom:
                configMapKeyRef:
                  name: billing-db-config
                  key: host
            - name: PG_BILLING_PORT
              valueFrom:
                configMapKeyRef:
                  name: billing-db-config
                  key: port
            - name: PG_BILLING_DB
              valueFrom:
                configMapKeyRef:
                  name: billing-db-config
                  key: db
            - name: PG_BILLING_USER
              valueFrom:
                secretKeyRef:
                  name: billing-db-creds
                  key: user
            - name: PG_BILLING_PASS
              valueFrom:
                secretKeyRef:
                  name: billing-db-creds
                  key: pass
      containers:
        - name: billing-consumer
          image: rhorv/wp-poc:19ccb6267ca9da27bf75773b827d1bf304ae8b09
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "/srv/run_billing.sh"]
          env:
            - name: PG_BILLING_HOST
              valueFrom:
                configMapKeyRef:
                  name: billing-db-config
                  key: host
            - name: PG_BILLING_PORT
              valueFrom:
                configMapKeyRef:
                  name: billing-db-config
                  key: port
            - name: PG_BILLING_DB
              valueFrom:
                configMapKeyRef:
                  name: billing-db-config
                  key: db
            - name: PG_BILLING_USER
              valueFrom:
                secretKeyRef:
                  name: billing-db-creds
                  key: user
            - name: PG_BILLING_PASS
              valueFrom:
                secretKeyRef:
                  name: billing-db-creds
                  key: pass
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: host
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: port
            - name: KAFKA_PRICING_EXTERNAL_TOPIC_NAME
              value: "pricing-payment"
            - name: KAFKA_BILLING_EXTERNAL_TOPIC_NAME
              value: "billing-payment"
            - name: KAFKA_BILLING_INTERNAL_TOPIC_NAME
              value: "billing-internal"
