apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-poc-clearing
  labels:
    app.wp.poc/name: wp-clearing
spec:
  replicas: 1
  selector:
    matchLabels:
      app.wp.poc/name: wp-clearing
  template:
    metadata:
      labels:
        app.wp.poc/name: wp-clearing
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: kafka-topic-setup
          image: rhorv/kafka-adm:latest
          command: ["sh", "-c", "/tmp/kafka_2.13-2.8.0/bin/kafka-topics.sh --create --if-not-exists --topic $${EXTERNAL_TOPIC_NAME} --bootstrap-server $${KAFKA_HOST}:$${KAFKA_PORT} && /tmp/kafka_2.13-2.8.0/bin/kafka-topics.sh --create --if-not-exists --topic $${INTERNAL_TOPIC_NAME} --bootstrap-server $${KAFKA_HOST}:$${KAFKA_PORT}"]
          env:
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: host
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: port
            - name: EXTERNAL_TOPIC_NAME
              value: "clearing-payment"
            - name: INTERNAL_TOPIC_NAME
              value: "clearing-internal"
      containers:
        - name: clearing-consumer
          image: rhorv/wp-poc:c72e5860f8017da9be5adff14c45866cf38983cd
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "/srv/run_clearing.sh"]
          env:
            - name: PG_CLEARING_HOST
              valueFrom:
                configMapKeyRef:
                  name: clearing-db-config
                  key: host
            - name: PG_CLEARING_PORT
              valueFrom:
                configMapKeyRef:
                  name: clearing-db-config
                  key: port
            - name: PG_CLEARING_DB
              valueFrom:
                configMapKeyRef:
                  name: clearing-db-config
                  key: db
            - name: PG_CLEARING_USER
              valueFrom:
                secretKeyRef:
                  name: clearing-db-creds
                  key: user
            - name: PG_CLEARING_PASS
              valueFrom:
                secretKeyRef:
                  name: clearing-db-creds
                  key: pass
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: host
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: port
            - name: KAFKA_CLEARING_EXTERNAL_TOPIC_NAME
              value: "clearing-payment"
            - name: KAFKA_CLEARING_INTERNAL_TOPIC_NAME
              value: "clearing-internal"
