apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-poc-clearing
  labels:
    app.wp.poc/name: wp-clearing
spec:
  replicas: 1
  selector:
    matchLabels:
      app.wp.poc/name: wp-clearing
  template:
    metadata:
      labels:
        app.wp.poc/name: wp-clearing
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: clearing-consumer
          image: rhorv/wp-poc:9bac3ed065a39e9e6988136a2acb4384b469c33d
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "/srv/bin/run_clearing.sh"]
          env:
            - name: PG_CLEARING_HOST
              valueFrom:
                configMapKeyRef:
                  name: clearing-db-config
                  key: host
            - name: PG_CLEARING_PORT
              valueFrom:
                configMapKeyRef:
                  name: clearing-db-config
                  key: port
            - name: PG_CLEARING_DB
              valueFrom:
                configMapKeyRef:
                  name: clearing-db-config
                  key: db
            - name: PG_CLEARING_USER
              valueFrom:
                secretKeyRef:
                  name: clearing-db-creds
                  key: user
            - name: PG_CLEARING_PASS
              valueFrom:
                secretKeyRef:
                  name: clearing-db-creds
                  key: pass
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: host
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: port
            - name: KAFKA_CLEARING_EXTERNAL_TOPIC_NAME
              value: "clearing-payment"
            - name: KAFKA_CLEARING_INTERNAL_TOPIC_NAME
              value: "clearing-internal"
